version: '3'

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: "first_db"
      POSTGRES_USER: "first_db_user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "md5"
  mysql:
    image: mysql:8.0.32
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: 'second_db'
      MYSQL_USER: 'second_db_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

